### ISSUE TITLE
Updating SMF 2.1 Beta 3 to PortaMx-Forum 2.1 Beta 4

### ISSUE THREAD

**Issue by Yariksat** [PortaMx/PortaMx-Forum#1]
I do everything according to the instructions. When you start upgrade.php PHP Parse error: syntax error, unexpected '==' (T_IS_EQUAL), expecting ')' in /home/admin/web/yarik-sat.ru/public_html/test/upgrade.php on line 5140

**Comment by PortaMx** [comment]
We will look at that ...

**Comment by Yariksat** [comment]
installation of a new forum successful, update failed

**Comment by PortaMx** [comment]
I think, this can be cosed at commit ed5021f

**Comment by Yariksat** [comment]
![4](https://cloud.githubusercontent.com/assets/17574854/16198780/ca584f00-370f-11e6-9561-dda98e83d4bb.png)
