### ISSUE TITLE
Senden von Announcements funktioniert nicht

### ISSUE THREAD

**Issue by AlexL777** [PortaMx/PortaMx-Forum#1]
Hallo Entwickler,

ich habe mir euer PortaMX-Forum sehr gerne angesehen und eine neue Forum-Installation in der Version 1.0 RC2 ermöglicht. Leider funktioniert das Senden der Forumankündigungen noch nicht. Der Balken mit Prozentzahl und dem "Done" wird nicht fertig und es lädt immer wieder nach.

Könnt ihr euch das bitte nochmals ansehen. 

Danke im Vorfeld.

P.S. ich habe dieses Repo geforkt und werde gerne die Weiterentwicklung von PortaMX Forum verfolgen. Auch meldete ich mich im offiziellen Support-Forum an, um auf dem Laufenden zu sein und zu bleiben. Danke!

**Comment by PortaMx** [comment]
Ich habe das eben mal getestet .. zwar nur mit wenigen mails, aber das lief einwandfrei ..
Vielleicht testest du mal nochmal mit wenigen mails.
Die einstellungen für eMail ist korrekt ? 
Bitte nochmal prüfen ...

**Comment by AlexL777** [comment]
Sehr seltsam, aber leider klappte es wieder nicht. Ich habe mehrfach gesendet. Ich habe auch in den Forum-Optionen meinen Mail-Account von GMX samt dem Port eingetragen. Ich bin im Forum ja alleine und so konnte ich nur an den Admin senden.

Wo kann ich bei PortaMX Announcements einstellen oder aktivieren oder sind sie von Haus aus aktiviert?! Ich habe etwas von den Alerts gefunden, aber dort stand nichts von Forum-Announcements.

Eine Frage nebenher: Gibt es schon ein deutsches Sprachpaket für die RC2 Version von PortaMX?

Danke im Vorfeld.

**Comment by PortaMx** [comment]
Newletter werden nur versendet wenn du das manuell machst.
Ansonsten werde nur automatisch mails versendet (über die Maintenace Functionen, wie z.B. daily oder weekly), wenn der user das aktiviert hat.
Eine Frage am Rande .. welche PHP Version verwendest Du auf deinem Server?
Und zu deiner letzten Frage .. Nein, es gibt noch kein Deutsches Sprachpaket .. aber vielleicht finden sich ja ein paar User, die das gerne mal machen wollen.
Für uns ist das der letzte Punkt auf der ToDo Liste .. zunächst mal muss das Forum sauber laufen und fehlerfrei laufen ...

**Comment by AlexL777** [comment]
OK, Danke für deine Antworten. Ich setze PHP 7.0 als Standard auf Managed Server unter Ubuntu 16.x ein. Kein Thema, ich freue mich, dass ich PortaMX Forum so entdeckte und damit arbeite dann ein bisschen, um erste Erfahrungen zu sammeln.

Auf das Update warte ich in jedem Falle 😄
