### ISSUE TITLE
Disclaimer-Link nicht korrekt im Forum-Footer

### ISSUE THREAD

**Issue by AlexL777** [PortaMx/PortaMx-Forum#2]
Hallo geehrter Entwickler,

ich konnte eben ein Upgrade auf die RC3 machen und vorher schon funktionierte der Disclaimer-Link im Footer nicht. Meine derzeitige PortaMX-Installation ist unter https://portamxforum.wpzweinull.ch. Klicke bitte im Footer auf Disclaimer.

Das führt dann zu einer Englisch-Variante, aber sie habe ich so nicht.
`https://portamxforum.wpzweinull.ch/https://portamxforum_english.wpzweinull.ch/#msg2`

Wie kann ich das Problem beheben?

Danke im Vorfeld.

**Comment by wintstar** [comment]
Hast du die Datei agreement.txt auch in Deutscher Sprache im Root? Siehe Screenshot
![agreement](https://cloud.githubusercontent.com/assets/2753863/26345797/57f7e1de-3fa4-11e7-8d31-101e98986d82.JPG)

**Comment by AlexL777** [comment]
Ja, habs eben das Sprachpaket für SMF 2.1 Beta 3 installiert. Leider funktioniert der Link weiterhin nicht. Ich lud die index.php sowohl aus dem Sprachpaket als auch von PortaMX Forum selbst mit hoch. Doch auch kein Resultat.

Als ob es falsch verlinkt ist, sollte aber funktionieren. Hm...Die Nutzungsbedingungen rechte Ecke im Footer sind übersetzt worden und auch anklickbar. Disclaimer leider nicht. 

Das kannst du dir bei bei nochmals ansehen. Jemand eine Idee, was nicht korrekt ist?

Danke im Vorfeld.

**Comment by wintstar** [comment]
Das  Sprachpaket für SMF 2.1 Beta 3 ist nicht kompatibel zu PortaMx Forum.  Schau im Admin Center 
Administration Center ►  Features and Options ►  General unter Link to a disclaimer.

> Here you can setup a link to a file or action, to show a Disclaimer for your Forum. You can use a PHP page or a Portal Block (PHP or HTML with php inside) for this. The link is inserted in the footer after the copyright. Note, that you NOT use the forum url here, these is automatically added.
> Examples for a link: mypages/disclaimer.php or ?spage=pagename (if the Portal enabled).
> The first example use the link forumurl/mypages/disclaimer.php?lang=language, where language is the users language (eg. "english", "german", the second example use the link forumurl/index.php?spage=pagename (this is a Portal singe Page) which can coded with a php block or html block (with php inside) where you detect the users language ($user_info['language']).

Wir sind gerade dabei ein deutsches Sprachpaket zu erstellen
(https://www.portamx.com/news-and-updates/current-status-of-portamx-forum/msg19573/#new)

**Comment by PortaMx** [comment]
Du kannst keine Sprachpakete von SMF verwenden .. die seind nicht kompatibel mit userer Forum Version.
Das gibt nur ärger und jede menge Fehlermeldungen ...

Wir arbeiten z.Z. an den deutschen Sprachdateien .. als bitte etwas gedult.

**Comment by AlexL777** [comment]
Danke euch beiden, habs erfasst und verstanden. Gleich wird umgesetzt 👍

**Comment by PortaMx** [comment]
Wenn Du problem hast, melde dich einfach bei uns im Forum an .. da gibt es dann auch support und hilfe.
Hier ist dafür nicht der richtige ort ...
