### ISSUE TITLE
Updating SMF 2.1 Beta 3 to PortaMx-Forum 2.1 Beta 4  Step 4: Database Changes

### ISSUE THREAD

**Issue by Yariksat** [PortaMx/PortaMx-Forum#2]
![4](https://cloud.githubusercontent.com/assets/17574854/16198875/31aa719c-3710-11e6-9ea8-8ee4bda792b3.png)

modification removed in step 1 requested files that do not - minified
[Mon Jun 20 17:13:57 2016] [error] [client 212.66.46.79] PHP Warning:  fwrite() expects parameter 1 to be resource, string given in /home/admin/web/yarik-sat.ru/public_html/upgrade.php on line 551, referer: https://yarik-sat.ru/upgrade.php?lang=english
[Mon Jun 20 17:13:57 2016] [error] [client 212.66.46.79] PHP Warning:  fclose() expects parameter 1 to be resource, string given in /home/admin/web/yarik-sat.ru/public_html/upgrade.php on line 552, referer: https://yarik-sat.ru/upgrade.php?lang=english
[Mon Jun 20 17:13:57 2016] [error] [client 212.66.46.79] PHP Notice:  Undefined index: login_token_var in /home/admin/web/yarik-sat.ru/public_html/upgrade.php on line 4712, referer: https://yarik-sat.ru/upgrade.php?lang=english
[Mon Jun 20 17:13:57 2016] [error] [client 212.66.46.79] PHP Notice:  Undefined index: login_token in /home/admin/web/yarik-sat.ru/public_html/upgrade.php on line 4712, referer: https://yarik-sat.ru/upgrade.php?lang=english
[Mon Jun 20 17:14:58 2016] [error] [client 212.66.46.79] PHP Warning:  fwrite() expects parameter 1 to be resource, string given in /home/admin/web/yarik-sat.ru/public_html/upgrade.php on line 551, referer: https://yarik-sat.ru/upgrade.php?step=0&substep=0&data=YTo2OntzOjc6ImN1cnN0ZXAiO2k6MDtzOjQ6ImxhbmciO3M6NzoiZW5nbGlzaCI7czozOiJyaWQiO2k6MzgzMTtzOjQ6InBhc3MiO2k6MDtzOjU6ImRlYnVnIjtpOjA7czoyOiJqcyI7aTowO30=
[Mon Jun 20 17:14:58 2016] [error] [client 212.66.46.79] PHP Warning:  fclose() expects parameter 1 to be resource, string given in /home/admin/web/yarik-sat.ru/public_html/upgrade.php on line 552, referer: https://yarik-sat.ru/upgrade.php?step=0&substep=0&data=YTo2OntzOjc6ImN1cnN0ZXAiO2k6MDtzOjQ6ImxhbmciO3M6NzoiZW5nbGlzaCI7czozOiJyaWQiO2k6MzgzMTtzOjQ6InBhc3MiO2k6MDtzOjU6ImRlYnVnIjtpOjA7czoyOiJqcyI7aTowO30=
[Mon Jun 20 17:14:58 2016] [error] [client 212.66.46.79] PHP Notice:  Undefined index: login_token_var in /home/admin/web/yarik-sat.ru/public_html/upgrade.php on line 4712, referer: https://yarik-sat.ru/upgrade.php?step=0&substep=0&data=YTo2OntzOjc6ImN1cnN0ZXAiO2k6MDtzOjQ6ImxhbmciO3M6NzoiZW5nbGlzaCI7czozOiJyaWQiO2k6MzgzMTtzOjQ6InBhc3MiO2k6MDtzOjU6ImRlYnVnIjtpOjA7czoyOiJqcyI7aTowO30=
[Mon Jun 20 17:14:58 2016] [error] [client 212.66.46.79] PHP Notice:  Undefined index: login_token in /home/admin/web/yarik-sat.ru/public_html/upgrade.php on line 4712, referer: https://yarik-sat.ru/upgrade.php?step=0&substep=0&data=YTo2OntzOjc6ImN1cnN0ZXAiO2k6MDtzOjQ6ImxhbmciO3M6NzoiZW5nbGlzaCI7czozOiJyaWQiO2k6MzgzMTtzOjQ6InBhc3MiO2k6MDtzOjU6ImRlYnVnIjtpOjA7czoyOiJqcyI7aTowO30=
[Mon Jun 20 17:15:26 2016] [error] [client 212.66.46.79] PHP Warning:  fwrite() expects parameter 1 to be resource, string given in /home/admin/web/yarik-sat.ru/public_html/upgrade.php on line 551, referer: https://yarik-sat.ru/upgrade.php?step=0&substep=0&data=YTo2OntzOjc6ImN1cnN0ZXAiO2k6MDtzOjQ6ImxhbmciO3M6NzoiZW5nbGlzaCI7czozOiJyaWQiO2k6MzgzMTtzOjQ6InBhc3MiO2k6MDtzOjU6ImRlYnVnIjtpOjA7czoyOiJqcyI7aTowO30=
[Mon Jun 20 17:15:26 2016] [error] [client 212.66.46.79] PHP Warning:  fclose() expects parameter 1 to be resource, string given in /home/admin/web/yarik-sat.ru/public_html/upgrade.php on line 552, referer: https://yarik-sat.ru/upgrade.php?step=0&substep=0&data=YTo2OntzOjc6ImN1cnN0ZXAiO2k6MDtzOjQ6ImxhbmciO3M6NzoiZW5nbGlzaCI7czozOiJyaWQiO2k6MzgzMTtzOjQ6InBhc3MiO2k6MDtzOjU6ImRlYnVnIjtpOjA7czoyOiJqcyI7aTowO30=
[Mon Jun 20 17:15:26 2016] [error] [client 212.66.46.79] PHP Notice:  Undefined index: login_token_var in /home/admin/web/yarik-sat.ru/public_html/upgrade.php on line 4712, referer: https://yarik-sat.ru/upgrade.php?step=0&substep=0&data=YTo2OntzOjc6ImN1cnN0ZXAiO2k6MDtzOjQ6ImxhbmciO3M6NzoiZW5nbGlzaCI7czozOiJyaWQiO2k6MzgzMTtzOjQ6InBhc3MiO2k6MDtzOjU6ImRlYnVnIjtpOjA7czoyOiJqcyI7aTowO30=
[Mon Jun 20 17:15:26 2016] [error] [client 212.66.46.79] PHP Notice:  Undefined index: login_token in /home/admin/web/yarik-sat.ru/public_html/upgrade.php on line 4712, referer: https://yarik-sat.ru/upgrade.php?step=0&substep=0&data=YTo2OntzOjc6ImN1cnN0ZXAiO2k6MDtzOjQ6ImxhbmciO3M6NzoiZW5nbGlzaCI7czozOiJyaWQiO2k6MzgzMTtzOjQ6InBhc3MiO2k6MDtzOjU6ImRlYnVnIjtpOjA7czoyOiJqcyI7aTowO30=
[Mon Jun 20 17:16:00 2016] [error] [client 107.178.195.171] File does not exist: /home/admin/web/yarik-sat.ru/public_html/javascript:void(0)
[Mon Jun 20 17:17:36 2016] [error] [client 212.66.46.79] PHP Warning:  fwrite() expects parameter 1 to be resource, string given in /home/admin/web/yarik-sat.ru/public_html/upgrade.php on line 551, referer: https://yarik-sat.ru/upgrade.php?step=0&substep=0&data=YTo2OntzOjc6ImN1cnN0ZXAiO2k6MDtzOjQ6ImxhbmciO3M6NzoiZW5nbGlzaCI7czozOiJyaWQiO2k6MzgzMTtzOjQ6InBhc3MiO2k6MDtzOjU6ImRlYnVnIjtpOjA7czoyOiJqcyI7aTowO30=
[Mon Jun 20 17:17:36 2016] [error] [client 212.66.46.79] PHP Warning:  fclose() expects parameter 1 to be resource, string given in /home/admin/web/yarik-sat.ru/public_html/upgrade.php on line 552, referer: https://yarik-sat.ru/upgrade.php?step=0&substep=0&data=YTo2OntzOjc6ImN1cnN0ZXAiO2k6MDtzOjQ6ImxhbmciO3M6NzoiZW5nbGlzaCI7czozOiJyaWQiO2k6MzgzMTtzOjQ6InBhc3MiO2k6MDtzOjU6ImRlYnVnIjtpOjA7czoyOiJqcyI7aTowO30=
[Mon Jun 20 17:17:36 2016] [error] [client 212.66.46.79] PHP Notice:  Undefined index: login_token_var in /home/admin/web/yarik-sat.ru/public_html/upgrade.php on line 4712, referer: https://yarik-sat.ru/upgrade.php?step=0&substep=0&data=YTo2OntzOjc6ImN1cnN0ZXAiO2k6MDtzOjQ6ImxhbmciO3M6NzoiZW5nbGlzaCI7czozOiJyaWQiO2k6MzgzMTtzOjQ6InBhc3MiO2k6MDtzOjU6ImRlYnVnIjtpOjA7czoyOiJqcyI7aTowO30=
[Mon Jun 20 17:17:36 2016] [error] [client 212.66.46.79] PHP Notice:  Undefined index: login_token in /home/admin/web/yarik-sat.ru/public_html/upgrade.php on line 4712, referer: https://yarik-sat.ru/upgrade.php?step=0&substep=0&data=YTo2OntzOjc6ImN1cnN0ZXAiO2k6MDtzOjQ6ImxhbmciO3M6NzoiZW5nbGlzaCI7czozOiJyaWQiO2k6MzgzMTtzOjQ6InBhc3MiO2k6MDtzOjU6ImRlYnVnIjtpOjA7czoyOiJqcyI7aTowO30=
[Mon Jun 20 17:18:37 2016] [error] [client 212.66.46.79] PHP Warning:  fwrite() expects parameter 1 to be resource, string given in /home/admin/web/yarik-sat.ru/public_html/upgrade.php on line 551, referer: https://yarik-sat.ru/upgrade.php?step=0&substep=0&data=YTo2OntzOjc6ImN1cnN0ZXAiO2k6MDtzOjQ6ImxhbmciO3M6NzoiZW5nbGlzaCI7czozOiJyaWQiO2k6MzgzMTtzOjQ6InBhc3MiO2k6MDtzOjU6ImRlYnVnIjtpOjA7czoyOiJqcyI7aTowO30=
[Mon Jun 20 17:18:37 2016] [error] [client 212.66.46.79] PHP Warning:  fclose() expects parameter 1 to be resource, string given in /home/admin/web/yarik-sat.ru/public_html/upgrade.php on line 552, referer: https://yarik-sat.ru/upgrade.php?step=0&substep=0&data=YTo2OntzOjc6ImN1cnN0ZXAiO2k6MDtzOjQ6ImxhbmciO3M6NzoiZW5nbGlzaCI7czozOiJyaWQiO2k6MzgzMTtzOjQ6InBhc3MiO2k6MDtzOjU6ImRlYnVnIjtpOjA7czoyOiJqcyI7aTowO30=
[Mon Jun 20 17:18:37 2016] [error] [client 212.66.46.79] PHP Notice:  Undefined index: login_token_var in /home/admin/web/yarik-sat.ru/public_html/upgrade.php on line 4712, referer: https://yarik-sat.ru/upgrade.php?step=0&substep=0&data=YTo2OntzOjc6ImN1cnN0ZXAiO2k6MDtzOjQ6ImxhbmciO3M6NzoiZW5nbGlzaCI7czozOiJyaWQiO2k6MzgzMTtzOjQ6InBhc3MiO2k6MDtzOjU6ImRlYnVnIjtpOjA7czoyOiJqcyI7aTowO30=
[Mon Jun 20 17:18:37 2016] [error] [client 212.66.46.79] PHP Notice:  Undefined index: login_token in /home/admin/web/yarik-sat.ru/public_html/upgrade.php on line 4712, referer: https://yarik-sat.ru/upgrade.php?step=0&substep=0&data=YTo2OntzOjc6ImN1cnN0ZXAiO2k6MDtzOjQ6ImxhbmciO3M6NzoiZW5nbGlzaCI7czozOiJyaWQiO2k6MzgzMTtzOjQ6InBhc3MiO2k6MDtzOjU6ImRlYnVnIjtpOjA7czoyOiJqcyI7aTowO30=
[Mon Jun 20 17:18:59 2016] [error] [client 212.66.46.79] PHP Warning:  fwrite() expects parameter 1 to be resource, string given in /home/admin/web/yarik-sat.ru/public_html/upgrade.php on line 551, referer: https://yarik-sat.ru/upgrade.php?step=0&substep=0&data=YTo2OntzOjc6ImN1cnN0ZXAiO2k6MDtzOjQ6ImxhbmciO3M6NzoiZW5nbGlzaCI7czozOiJyaWQiO2k6MzgzMTtzOjQ6InBhc3MiO2k6MDtzOjU6ImRlYnVnIjtpOjA7czoyOiJqcyI7aTowO30=
[Mon Jun 20 17:18:59 2016] [error] [client 212.66.46.79] PHP Warning:  fclose() expects parameter 1 to be resource, string given in /home/admin/web/yarik-sat.ru/public_html/upgrade.php on line 552, referer: https://yarik-sat.ru/upgrade.php?step=0&substep=0&data=YTo2OntzOjc6ImN1cnN0ZXAiO2k6MDtzOjQ6ImxhbmciO3M6NzoiZW5nbGlzaCI7czozOiJyaWQiO2k6MzgzMTtzOjQ6InBhc3MiO2k6MDtzOjU6ImRlYnVnIjtpOjA7czoyOiJqcyI7aTowO30=
[Mon Jun 20 17:18:59 2016] [error] [client 212.66.46.79] PHP Notice:  Undefined index: login_token_var in /home/admin/web/yarik-sat.ru/public_html/upgrade.php on line 4712, referer: https://yarik-sat.ru/upgrade.php?step=0&substep=0&data=YTo2OntzOjc6ImN1cnN0ZXAiO2k6MDtzOjQ6ImxhbmciO3M6NzoiZW5nbGlzaCI7czozOiJyaWQiO2k6MzgzMTtzOjQ6InBhc3MiO2k6MDtzOjU6ImRlYnVnIjtpOjA7czoyOiJqcyI7aTowO30=
[Mon Jun 20 17:18:59 2016] [error] [client 212.66.46.79] PHP Notice:  Undefined index: login_token in /home/admin/web/yarik-sat.ru/public_html/upgrade.php on line 4712, referer: https://yarik-sat.ru/upgrade.php?step=0&substep=0&data=YTo2OntzOjc6ImN1cnN0ZXAiO2k6MDtzOjQ6ImxhbmciO3M6NzoiZW5nbGlzaCI7czozOiJyaWQiO2k6MzgzMTtzOjQ6InBhc3MiO2k6MDtzOjU6ImRlYnVnIjtpOjA7czoyOiJqcyI7aTowO30=
[Mon Jun 20 17:24:20 2016] [error] [client 212.66.46.79] PHP Warning:  fwrite() expects parameter 1 to be resource, string given in /home/admin/web/yarik-sat.ru/public_html/upgrade.php on line 551, referer: https://yarik-sat.ru/upgrade.php?lang=english
[Mon Jun 20 17:24:20 2016] [error] [client 212.66.46.79] PHP Warning:  fclose() expects parameter 1 to be resource, string given in /home/admin/web/yarik-sat.ru/public_html/upgrade.php on line 552, referer: https://yarik-sat.ru/upgrade.php?lang=english
[Mon Jun 20 17:24:20 2016] [error] [client 212.66.46.79] PHP Notice:  Undefined index: login_token_var in /home/admin/web/yarik-sat.ru/public_html/upgrade.php on line 4712, referer: https://yarik-sat.ru/upgrade.php?lang=english

**Comment by PortaMx** [comment]
This 106f17d fixed the issue on update amin:info_files ..

**Comment by Yariksat** [comment]
When updating files which are not requested
![5](https://cloud.githubusercontent.com/assets/17574854/16202405/3b16c1e6-371e-11e6-9204-b76a9cfd8ef5.png)
![7](https://cloud.githubusercontent.com/assets/17574854/16202406/3b1811f4-371e-11e6-8e85-d4884d5dcbf6.png)
the update was successful, then came such characters IP
![9](https://cloud.githubusercontent.com/assets/17574854/16202605/0bf79f6a-371f-11e6-8706-32ead5bca401.png)
after some time the forum has stopped working
[Mon Jun 20 19:40:08 2016] [error] [client 213.230.73.234] PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 77 bytes) in /home/admin/web/yarik-sat.ru/public_html/Sources/Subs-Db-mysqli.php on line 823
[Mon Jun 20 19:40:09 2016] [error] [client 188.113.203.112] PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 32 bytes) in /home/admin/web/yarik-sat.ru/public_html/Sources/Subs-Db-mysqli.php on line 823
[Mon Jun 20 19:40:13 2016] [error] [client 213.230.73.234] PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 77 bytes) in /home/admin/web/yarik-sat.ru/public_html/Sources/Subs-Db-mysqli.php on line 823, referer: https://yarik-sat.ru/index.php?topic=642.msg46285
[Mon Jun 20 19:40:25 2016] [error] [client 213.230.73.234] PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 77 bytes) in /home/admin/web/yarik-sat.ru/public_html/Sources/Subs-Db-mysqli.php on line 823
[Mon Jun 20 19:40:31 2016] [error] [client 213.230.73.234] PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 77 bytes) in /home/admin/web/yarik-sat.ru/public_html/Sources/Subs-Db-mysqli.php on line 823
[Mon Jun 20 19:40:37 2016] [error] [client 213.230.73.234] PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 72 bytes) in /home/admin/web/yarik-sat.ru/public_html/Sources/Subs-Db-mysqli.php on line 823, referer: https://yarik-sat.ru/index.php?topic=642.msg46285
[Mon Jun 20 19:40:41 2016] [error] [client 213.230.73.234] PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 64 bytes) in /home/admin/web/yarik-sat.ru/public_html/Sources/Subs-Db-mysqli.php on line 823
[Mon Jun 20 19:40:57 2016] [error] [client 188.113.203.112] PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 72 bytes) in /home/admin/web/yarik-sat.ru/public_html/Sources/Subs-Db-mysqli.php on line 823
[Mon Jun 20 19:41:09 2016] [error] [client 212.66.46.79] PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 72 bytes) in /home/admin/web/yarik-sat.ru/public_html/Sources/Subs-Db-mysqli.php on line 823, referer: https://yarik-sat.ru/index.php?action=who
[Mon Jun 20 19:41:20 2016] [error] [client 212.66.46.79] PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 72 bytes) in /home/admin/web/yarik-sat.ru/public_html/Sources/Subs-Db-mysqli.php on line 823, referer: https://yarik-sat.ru/

**Comment by PortaMx** [comment]
What PHP version you use?
I tested a upgrade, but only the admin_prefereces in the theme file needs a fix on the upgrade.php, what I just have commit

**Comment by Yariksat** [comment]
PHP Version 	5.4.45-0+deb7u2

**Comment by PortaMx** [comment]
Well .. I just upgrade my old forum with many topics and user without any problem.
So I can't currently solve your problem ..
In the other hand .. it's nor planned to upgrade a SMF 2.1 Beta release

**Comment by Yariksat** [comment]
It is a pity, really liked the improvements.
I'll wait for the update from the SMF team
